apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    run: app1
spec:
  type: {{ .Values.serviceType }}
  selector:
    run: app1
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
