apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
  labels:
    app: app1
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: app1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: app1
    spec:
      containers:
        - name: php-fpm
          image: eu.gcr.io/zoover-assignment-rafael/zoover-php-app:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 9000
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9000
            failureThreshold: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "256Mi"
        - name: nginx
          image: eu.gcr.io/zoover-assignment-rafael/zoover-php-app-nginx:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /app1
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 80
              protocol: TCP
              hostPort: 8081
          readinessProbe:
            httpGet:
              path: /app1
              port: 80
            failureThreshold: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "20m"
              memory: "64Mi"
      dnsPolicy: ClusterFirst
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "php-fpm"
      restartPolicy: Always
