version: "3.8"

services:
  php-fpm:
    build: ../files/dev/php-fpm
    volumes:
      - ../../app:/app:delegated
    working_dir: /app
    environment:
      AM_I_INSIDE_DOCKER: "true"

  nginx:
    image: nginx:1.19.2-alpine
    ports:
      - 8080:80
    volumes:
      - ../../app/public:/app/public:ro
      - ../res/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php-fpm
