apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zoover-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
{{- if .Values.certificateManagerLetsEncryptEnabled }}
    cert-manager.io/issuer: {{ .Values.issuerName }}
  {{- if .Values.ingressHostname }}
    kubernetes.io/ingress.global-static-ip-name: zoover-ingress-ip
  {{- end }}
{{- else }}
    cert-manager.io/issuer: selfsigned-issuer
{{- end }}
{{/*  {{- if .Values.ingressHostname }}*/}}
{{/*    ingress.kubernetes.io/force-ssl-redirect: "true"*/}}
{{/*  {{- end }}*/}}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: app2
              servicePort: 8082
          - path: /app1
            backend:
              serviceName: app1
              servicePort: 8081
          - path: /app2
            backend:
              serviceName: app2
              servicePort: 8082
    {{- if .Values.ingressHostname }}
      host: {{ .Values.ingressHostname }}
    {{- end }}
{{- if .Values.ingressHostname }}
  tls:
    - hosts:
        - {{ .Values.ingressHostname }}
      secretName: {{ .Values.ingressHostname }}-{{ .Values.issuerName }}-cert
{{- end }}
