apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    run: app2
spec:
  type: {{ .Values.serviceType }}
  selector:
    run: app2
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 80
